name: builds docker image

on:
  push

jobs:
  build:
    name: builds 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max